import {Client} from "fnapicom";
import {BRStatsByAccountIDResponseData} from "fnapicom/dist/src/http/autogeneratedEndpointStructs";

// class FortniteApi {
//   public getProfileByUsername(username: string) {
//
//     let fortniteProfile: any;
//
//     fetch(`https://fortnite-api.com/v2/stats/br/v2?name=${encodeURIComponent(username)}`, {
//       headers: {
//         Authorization: "442ebed4-083d-4e07-af54-2f6ba429a4a9",
//       },
//     })
//       .then((res: any) => res.json())
//       .then((responseJson) => {
//         fortniteProfile = responseJson
//       })
//       .catch((err) => {
//         console.log('err', err)
//       })
//
//     return fortniteProfile
//   }
// }

const client = new Client({
  // language: Language.Spanish,
  apiKey: '442ebed4-083d-4e07-af54-2f6ba429a4a9',
});

const configurationApi = {
  headers: {
    Authorization: "442ebed4-083d-4e07-af54-2f6ba429a4a9",
  },
}

const getProfileByUsername = async (fortniteUser: string): Promise<BRStatsByAccountIDResponseData> => {
  let fortniteProfile: any;

  await fetch(`https://fortnite-api.com/v2/stats/br/v2?name=${encodeURIComponent(fortniteUser)}`, configurationApi)
    .then((res: any) => res.json())
    .then((responseJson) => {
      fortniteProfile = responseJson
    })
    .catch((err) => {
      console.log('err', err)
    })

  console.log(fortniteProfile)
  return fortniteProfile

}

export {
  getProfileByUsername,
}