import {Language} from "fnapicom";
import {BRStatsByAccountIDResponseData} from "fnapicom/dist/src/http/autogeneratedEndpointStructs";
import {ClientOptions} from "fnapicom/dist/resources/structs";

// class FortniteApi {
//   public getProfileByUsername(username: string) {
//
//     let fortniteProfile: any;
//
//     fetch(`https://fortnite-api.com/v2/stats/br/v2?name=${encodeURIComponent(username)}`, {
//       headers: {
//         Authorization: "442ebed4-083d-4e07-af54-2f6ba429a4a9",
//       },
//     })
//       .then((res: any) => res.json())
//       .then((responseJson) => {
//         fortniteProfile = responseJson
//       })
//       .catch((err) => {
//         console.log('err', err)
//       })
//
//     return fortniteProfile
//   }
// }

export class FortniteService {

  public async getProfileByUsername(fortniteUser: string): Promise<BRStatsByAccountIDResponseData> {
    let fortniteProfile: any;

    await fetch(`https://fortnite-api.com/v2/stats/br/v2?name=${encodeURIComponent(fortniteUser)}`, this.ApiConfig())
      .then((res: any) => res.json())
      .then((responseJson) => {
        fortniteProfile = responseJson
      })
      .catch((err) => {
        console.log('err', err)
      });

    return fortniteProfile
  }

  public async getProfileById(fortniteId: string): Promise<BRStatsByAccountIDResponseData> {
    let fortniteProfile: any;

    await fetch(`https://fortnite-api.com/v2/stats/br/v2/${encodeURIComponent(fortniteId)}`, this.ApiConfig())
      .then((res: any) => res.json())
      .then((responseJson) => {
        fortniteProfile = responseJson
      })
      .catch((err) => {
        console.log('err', err)
      });

    return fortniteProfile
  }

  private ApiConfig(client?: boolean): any {
    if (client) {
      return {
        language: Language.Spanish,
        apiKey: '442ebed4-083d-4e07-af54-2f6ba429a4a9',
      } as ClientOptions
    }

    return {
      headers: {
        Authorization: "442ebed4-083d-4e07-af54-2f6ba429a4a9",
      }
    } as IFortniteApiConfig;

    // const fortniteApiConfig: IFortniteApiConfig = {
    //   headers: {
    //     Authorization: "442ebed4-083d-4e07-af54-2f6ba429a4a9",
    //   },
    // }
    // const fortniteClientApiConfig: ClientOptions = {
    //   language: Language.Spanish,
    //   apiKey: '442ebed4-083d-4e07-af54-2f6ba429a4a9',
    // }
    // return (client ? fortniteClientApiConfig : fortniteApiConfig)
  }
}

// INTERFACES
interface IFortniteApiConfig {
  headers: IFortniteApiHeaderConfig
}

interface IFortniteApiHeaderConfig {
  Authorization: string
}
