import {Button, StyleSheet, Text, TextInput, View} from 'react-native';
import {Colors} from "@/constants/Colors";
import {Client, Language} from "fnapicom";
import {getProfileByUsername} from "@/app/services/fortniteClient/fortnite";
import {BRStatsByAccountIDResponseData} from "fnapicom/dist/src/http/autogeneratedEndpointStructs";

export default function StatsScreen({route}: any) {

  const {fortniteUsername} = route.params;

  const client = new Client({
    language: Language.Spanish,
    apiKey: '442ebed4-083d-4e07-af54-2f6ba429a4a9',
  });

  const searchProfile = () => {
    console.log('--------')
    const profile = getProfileByUsername(fortniteUsername)


    profile.then((res: BRStatsByAccountIDResponseData) => {
      console.log(res.data.account.name)
    })
  }

  return (
    <View style={{
      backgroundColor: Colors.primary,
      height: '100%',
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center'
    }}>
      <Text>
        imagen
      </Text>
      <TextInput placeholder={'Buscar'}>
      </TextInput>
      <Button title={'Buscar'} onPress={() => searchProfile()}></Button>
    </View>
  );
}

const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepContainer: {
    gap: 8,
    marginBottom: 8,
  },
  reactLogo: {
    height: 178,
    width: 290,
    bottom: 0,
    left: 0,
    position: 'absolute',
  },
});
